### ISSUE TITLE
Exclude beta and special versions from "latest" browser version

### ISSUE THREAD

**Issue by tboyce** [klamping/browserstack-capabilities#10]
Might be nice to have a way to exclude beta and special versions (e.g. IE 10 Metro).

**Comment by localjo** [comment]
`browserstack-runner` has keywords for current and previous versions. https://github.com/browserstack/browserstack-runner#compact-browsers-configuration

I think it could be useful to have keywords `current`(stable), `previous`(stable -1), and `latest`(betas).

**Comment by tboyce** [comment]
Renamed the option to current and excluded betas. Previous and latest not implemented at this time.

**Comment by tboyce** [comment]
@localjo your suggestion has been implemented
