### ISSUE TITLE
Add tool to update "browsers.json" file

### ISSUE THREAD

**Issue by klamping** [klamping/browserstack-capabilities#2]
Currently, `browsers.json` is a static file pulled down from the Browserstack JSON API in a one-time request. To make updates easier, have a function that pulls down the latest information and replaces the file.

**Comment by tboyce** [comment]
Implemented by pulling the browsers.json from the Browserstack API at runtime. Making this a separate function might be something to consider, but could complicate usage of the library in some scenarios.
